"""Stable Messenger postback / quick_reply payload strings — Nhịp 1 baseline (CP1)."""

from __future__ import annotations

# --- Entry CTAs (new_user_* intake) ---
TV_ENTRY_LOVE = "TV_ENTRY_LOVE"
TV_ENTRY_CAREER = "TV_ENTRY_CAREER"
TV_ENTRY_ORGANIC_GENERAL = "TV_ENTRY_ORGANIC_GENERAL"

# --- Interest rescue (new_user_general) ---
TV_INTEREST_LOVE = "TV_INTEREST_LOVE"
TV_INTEREST_CAREER = "TV_INTEREST_CAREER"
TV_INTEREST_PATH_GENERAL = "TV_INTEREST_PATH_GENERAL"

# --- intake_abandoned_resume ---
TV_INTAKE_RESUME = "TV_INTAKE_RESUME"
TV_INTAKE_EDIT = "TV_INTAKE_EDIT"

# --- CTA sau free (primary / secondary) ---
TV_CTA_DEEP_LOVE = "TV_CTA_DEEP_LOVE"
TV_CTA_DEFER_LOVE = "TV_CTA_DEFER_LOVE"
TV_CTA_DEEP_CAREER = "TV_CTA_DEEP_CAREER"
TV_CTA_DEFER_CAREER = "TV_CTA_DEFER_CAREER"
TV_CTA_DEEP_GENERAL = "TV_CTA_DEEP_GENERAL"
TV_CTA_DEFER_GENERAL = "TV_CTA_DEFER_GENERAL"
TV_CTA_PRIMARY_RETURNING_UNPAID = "TV_CTA_PRIMARY_RETURNING_UNPAID"
TV_CTA_SECONDARY_RETURNING_UNPAID = "TV_CTA_SECONDARY_RETURNING_UNPAID"
TV_CTA_PRIMARY_PAID_REPEAT = "TV_CTA_PRIMARY_PAID_REPEAT"
TV_CTA_SECONDARY_PAID_REPEAT = "TV_CTA_SECONDARY_PAID_REPEAT"

# --- Universal confirm / calendar / gender (baseline) ---
TV_CONFIRM_OK = "TV_CONFIRM_OK"
TV_CONFIRM_EDIT_INFO = "TV_CONFIRM_EDIT_INFO"
TV_CAL_SOLAR = "TV_CAL_SOLAR"
TV_CAL_LUNAR = "TV_CAL_LUNAR"
TV_GENDER_MALE = "TV_GENDER_MALE"
TV_GENDER_FEMALE = "TV_GENDER_FEMALE"

# --- Universal offer ---
TV_OFFER_OPEN_PAYMENT = "TV_OFFER_OPEN_PAYMENT"
TV_OFFER_NEED_HUMAN = "TV_OFFER_NEED_HUMAN"

ALL_BASELINE_PAYLOADS: frozenset[str] = frozenset(
    {
        TV_ENTRY_LOVE,
        TV_ENTRY_CAREER,
        TV_ENTRY_ORGANIC_GENERAL,
        TV_INTEREST_LOVE,
        TV_INTEREST_CAREER,
        TV_INTEREST_PATH_GENERAL,
        TV_INTAKE_RESUME,
        TV_INTAKE_EDIT,
        TV_CTA_DEEP_LOVE,
        TV_CTA_DEFER_LOVE,
        TV_CTA_DEEP_CAREER,
        TV_CTA_DEFER_CAREER,
        TV_CTA_DEEP_GENERAL,
        TV_CTA_DEFER_GENERAL,
        TV_CTA_PRIMARY_RETURNING_UNPAID,
        TV_CTA_SECONDARY_RETURNING_UNPAID,
        TV_CTA_PRIMARY_PAID_REPEAT,
        TV_CTA_SECONDARY_PAID_REPEAT,
        TV_CONFIRM_OK,
        TV_CONFIRM_EDIT_INFO,
        TV_CAL_SOLAR,
        TV_CAL_LUNAR,
        TV_GENDER_MALE,
        TV_GENDER_FEMALE,
        TV_OFFER_OPEN_PAYMENT,
        TV_OFFER_NEED_HUMAN,
    }
)
